services:
  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/prometheus/'
      - '--web.external-url=http://prometheus:9090/prometheus/'
      # use http://prometheus:9090/prometheus to connect to datasourse from Grafana container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus      
    networks:
      - monitoring_network

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox_exporter
    ports:
      - "9115:9115"
    volumes:
      - ./blackbox.yml:/etc/blackbox_exporter/config.yml
    networks:
      - monitoring_network
    extra_hosts: # for /etc/hosts inside the container if need special resolve
      - "example.com:10.172.1.90"

  proxy:
    image: nginx:1.25.4
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/ssl/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
    networks:
      - monitoring_network

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SERVER_ROOT_URL=http://grafana:3000/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring_network


  node-exporter:
    image: prom/node-exporter:v1.8.2
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
    restart: unless-stopped
    networks:
      - monitoring_network


networks:
  monitoring_network:
    driver: bridge

volumes:
  prometheus_data:
  grafana-storage:
